name: Assign Labels on PR by Team
on:
  pull_request:
    types: [opened]
jobs:
  add-labels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        team-config:
          - name: miraito
            members: ucan-lab,toshikatsu-tsuzuki,y-horikoshi-miraito,t-kurumagawa,kakiuchi-miraito
            label: team:ミライト
#           - name: example-team
#             members: example-user1,example-user2
#             label: team: example
    steps:
      - name: Check if PR creator is in the current team
        id: check_user
        run: |
          echo "is_team_member=false" >> $GITHUB_ENV
          if [[ ",${{ matrix.team-config.members }}," == *",${{ github.actor }},"* ]]; then
            echo "is_team_member=true" >> $GITHUB_ENV
          fi
      - name: Assign Team Label using GitHub API
        if: env.is_team_member == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
            -d "{\"labels\":[\"${{ matrix.team-config.label }}\"]}"
